application: games1001
version: 1
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: webapp2
  version: latest
  
handlers:
- url: /js
  static_dir: js 

# This allows to use urls like this "js/script.js" in html 
- url: /game/js
  static_dir: js 

- url: /images
  static_dir: images
   
# This allows to use urls like this "js/script.js" in html 
- url: /game/images
  static_dir: images 

- url: /.*
  script: main.app
  
